---
- name: kernel source
  dnf:
    name: "{{ packages }}-{{ ansible_kernel }}"
    state: installed
    enablerepo: powertools
  vars:
    packages:
    - kernel
    - kernel-core
    - kernel-devel
    - kernel-doc
    - kernel-headers
    - kernel-modules
    - kernel-modules-extra
    - kernel-tools
    - kernel-tools-libs
    - kernel-tools-libs-devel

- name: Asterisk Dependencies
  dnf:
    name: "{{ packages }}"
    state: latest
    enablerepo: powertools
  vars:
    packages:
    - '@Development tools'
    - jq
    - lynx
    - mailx
    - screen
    - net-tools
    - libpq-devel
    - libedit-devel
    - libuuid-devel
    - libxml2-devel
    - sqlite-devel
    - systemd-devel
